# Generated by Django 3.0 on 2020-09-22 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicmp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apicmp.Pais')),
            ],
            options={
                'verbose_name_plural': 'Universidades',
            },
        ),
        migrations.CreateModel(
            name='ProgramaU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('universidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apicmp.Pais')),
            ],
            options={
                'verbose_name_plural': 'ProgramasU',
            },
        ),
        migrations.CreateModel(
            name='PesoU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apicmp.Area')),
                ('programau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apicmp.ProgramaU')),
            ],
            options={
                'verbose_name_plural': 'PesosU',
            },
        ),
    ]
