# Generated by Django 3.0 on 2020-09-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicmp', '0003_auto_20200922_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='numeral',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
