# Generated by Django 3.0 on 2020-09-23 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicmp', '0004_grupo_numeral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['numeral'], 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['numeral'], 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['id'], 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='peso',
            options={'ordering': ['id'], 'verbose_name_plural': 'Pesos'},
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ['id'], 'verbose_name_plural': 'Programas'},
        ),
        migrations.AlterModelOptions(
            name='programau',
            options={'ordering': ['id'], 'verbose_name_plural': 'ProgramasU'},
        ),
        migrations.AlterField(
            model_name='area',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='apicmp.Grupo'),
        ),
    ]
