# Generated by Django 3.0 on 2020-09-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicmp', '0006_auto_20200924_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesou',
            name='programau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesosu', to='apicmp.ProgramaU'),
        ),
    ]
