# Generated by Django 3.0 on 2020-09-30 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicmp', '0007_auto_20200928_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesou',
            options={'ordering': ['area'], 'verbose_name_plural': 'PesosU'},
        ),
    ]
